config/routes.rb
NewsReader2::Application.routes.draw do
  resources :keywords

  resources :subcats

  resources :categories

  resources :genres

  root :to => "articles#index"

  resources :articles
  
  

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  #==========================
  # Relations
  #==========================
  #
  has_many :category

end#class Genre

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # Layout
  layout "admin"
  
  # GET /genres
  # GET /genres.json
  def index
    # doc => http://stackoverflow.com/questions/742700/rails-active-record-findall-order-issue
    @genres = Genre.find(:all, :order => "name DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genre = Genre.find(params[:id])
    
    # Categories
    # @categories = @genre.category
    @categories = Category.find_all_by_genre_id(params[:id], :order => "name")
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.json
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render json: @genre, status: :created, location: @genre }
      else
        format.html { render action: "new" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.json
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Listing genres</h1>

<table>
  <tr>
  	<th>Id</th>
    <th>Name</th>
  </tr>

<% @genres.each do |genre| %>
  <tr>
  	<td><%= genre.id %></td>
    <td><%= link_to genre.name, genre %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Genre', new_genre_path %>&nbsp;|&nbsp;

app/views/genres/new.html.erb
<h1><%= t('controller_new.New') + t('controller_new.genre') %></h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Genre</h1>

<p>
  <b>ID: </b>
  <%= @genre.id %>
</p>

<!-- doc => http://rails3try.blogspot.jp/2012/01/rails3-i18n.html -->

<p>
  <b><%= t('Name')%>: </b>
  <%= @genre.name %>
</p>

<p><b>Categories:</b><br />
	<% if @categories.length != 0 %>
		
		<% @categories.each do |category| %>
			<%= category.id %>. <%= link_to category.name, category %><br />
		<% end %>
		
	<% else %>
		@categories => nil!
	<% end %>
</p>

<p>
	<%#= link_to 'Add category', new_category_path, :genre_id => @genre.id %>
	<%#= link_to 'Add category', new_category_path, :method => 'get', :genre_id => @genre.id %>
	<%= link_to 'Add category', :controller => 'categories', :action => 'new', :genre_id => @genre.id %>
</p>

<br />

<%= link_to t('scaffold_labels.Edit'), edit_genre_path(@genre) %> |
<%= link_to t('scaffold_labels.Back'), genres_path %>&nbsp;&nbsp;|&nbsp;
<%= link_to t('scaffold_labels.Destroy'), @genre, confirm: 'Are you sure?', method: :delete, :style => "color: red;" %>