config/routes.rb
NewsReader2::Application.routes.draw do
  resources :keywords

  resources :subcats

  resources :categories

  resources :genres

  root :to => "articles#index"

  resources :articles
  
  

end

app/models/subcat.rb
class Subcat < ActiveRecord::Base
  belongs_to :category
end

app/controllers/subcats_controller.rb
class SubcatsController < ApplicationController
  # Layout
  layout "admin"

  # GET /subcats
  # GET /subcats.json
  def index
    @subcats = Subcat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subcats }
    end
  end

  # GET /subcats/1
  # GET /subcats/1.json
  def show
    @subcat = Subcat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subcat }
    end
  end

  # GET /subcats/new
  # GET /subcats/new.json
  def new
    @subcat = Subcat.new
  
    @categories = Category.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subcat }
    end
  end

  # GET /subcats/1/edit
  def edit
    @subcat = Subcat.find(params[:id])
  end

  # POST /subcats
  # POST /subcats.json
  def create
    @subcat = Subcat.new(params[:subcat])

    respond_to do |format|
      if @subcat.save
        format.html { redirect_to @subcat, notice: 'Subcat was successfully created.' }
        format.json { render json: @subcat, status: :created, location: @subcat }
      else
        format.html { render action: "new" }
        format.json { render json: @subcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subcats/1
  # PUT /subcats/1.json
  def update
    @subcat = Subcat.find(params[:id])

    respond_to do |format|
      if @subcat.update_attributes(params[:subcat])
        format.html { redirect_to @subcat, notice: 'Subcat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcats/1
  # DELETE /subcats/1.json
  def destroy
    @subcat = Subcat.find(params[:id])
    @subcat.destroy

    respond_to do |format|
      format.html { redirect_to subcats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subcats_helper.rb
module SubcatsHelper
end

app/views/subcats/_form.html.erb
<%= form_for(@subcat) do |f| %>
  <% if @subcat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcat.errors.count, "error") %> prohibited this subcat from being saved:</h2>

      <ul>
      <% @subcat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%#= f.number_field :category_id %>
    
    <%#= f.select :category_id, @categories {|c| [c.id, c.name]} %>
    <%#= f.select :category_id, Category.all.collect {|c| [c.id, c.name]} %>
    <%= f.select :category_id, Category.all.collect {|c| [c.name, c.id]} %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcats/edit.html.erb
<h1>Editing subcat</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcat %> |
<%= link_to 'Back', subcats_path %>

app/views/subcats/index.html.erb
<h1>Listing subcats</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subcats.each do |subcat| %>
  <tr>
    <td><%= subcat.name %></td>
    <td><%= subcat.category.name %>(id=<%= subcat.category.id %>)</td>
    <td><%= link_to 'Show', subcat %></td>
    <td><%= link_to 'Edit', edit_subcat_path(subcat) %></td>
    <td><%= link_to 'Destroy', subcat, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subcat', new_subcat_path %>&nbsp;|&nbsp;

app/views/subcats/new.html.erb
<h1>New subcat</h1>

<%= render 'form' %>

<%= link_to 'Back', subcats_path %>

<hr />
<%#= @categories %>

app/views/subcats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @subcat.name %>
</p>

<p>
  <b>Category:</b>
  <%= @subcat.category.name %>(id=<%= @subcat.category.id %>)
</p>


<%= link_to 'Edit', edit_subcat_path(@subcat) %> |
<%= link_to 'Back', subcats_path %>