config/routes.rb
NewsReader2::Application.routes.draw do
  resources :keywords

  resources :subcats

  resources :categories

  resources :genres

  root :to => "articles#index"

  resources :articles
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  #==========================
  # Relations
  #==========================
  #
  belongs_to :genre
  has_many :subcat  

end#class Category

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # Layout
  layout "admin"

  #==========================
  # Methods
  #==========================

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    
    # Get params
    # @genre_id = params[':genre_id']
    @genre_id = params[:genre_id]
    
    if @genre_id != nil
      @category.genre_id = @genre_id
    end
    
    # @genres = Genre.all
#     
    # @genre_names = []
#     
    # @genres.each do |item|
      # @genre_names.push(item.name)
    # end
# 
    # # reset_id
#     
    # @cats = Category.find_all_by_genre_id(2)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private #==========================================
  #-------------------------------
  # reset_id
  # 1. Delete all records and rest the auto-increment number  
  #-------------------------------
  def reset_id
    ActiveRecord::Base.connection.execute(\
          #'ALTER TABLE category AUTO_INCREMENT = 1')
          # "DELETE FROM sqlite_sequence WHERE NAME = 'cate'")
          # "DELETE FROM sqlite_sequence WHERE NAME = 'categories'")
          "DELETE FROM categories; DELETE FROM sqlite_sequence WHERE NAME = 'categories'")
    
    #
    # @adapter = ActiveRecord::Base.connection.adapter_name
#     
    # @key = maximum(primary_key)

  end#def reset_id

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br />
		<!-- Ref => http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-select     -->
    
    <% if @category.genre_id != nil %>
	    <%= select("category", "genre_id", 
	    			Genre.all.collect {|g| [g.name, g.id]}, 
	    			{:include_blank => true, :selected => @category.genre_id}) %>
    <% else %>
	    <%= select("category", "genre_id", 
	    			Genre.all.collect {|g| [g.name, g.id]}, 
	    			{:include_blank => true}) %>
    <% end %>
    
    <%#= f.number_field :genre_id %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<!-- @cats => <%#= @cats %>(<%#=@cats.size.to_s %>) -->

<%#= @adapter %>

<!--   <div class="field"> -->
    <%#= f.label :genre_id %><br />
    <%#= f.number_field :genre_id %>
<!--   </div> -->

<%#= f.collection_select :genre_id, @genre_names, :to_s, :to_s, :include_blank => true %>
<%#= f.select :name, @genres, :selected => params[:id] %>
<%#= select("post", "genre_id", Genre.all.collect {|g| [g.name, g.id]}, {:include_blank => true}) %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
  	<th>Id</th>
    <th>Name</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
  	<td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.genre_id %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>&nbsp;|&nbsp;

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>


<%= link_to 'Back', categories_path %>&nbsp;&nbsp;|

<% if @category.genre_id != nil %>
	<%= link_to 'Back to genre', @category.genre %>
<% else %>
	<%= link_to 'Back to genres list', genres_path %>
<% end %>

<hr />
@category.genre_id => <%= @category.genre_id %><br />
@genre_id => <%= @genre_id %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Genre:</b>
  <%= link_to @category.genre.name, @category.genre %>&nbsp;(id=<%= @category.genre_id %>)
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>&nbsp;&nbsp;|
<%= link_to 'Back to genres list', genres_path %>