config/routes.rb
NewsReader2::Application.routes.draw do
  resources :keywords

  resources :subcats

  resources :categories

  resources :genres

  root :to => "articles#index"

  resources :articles
  
  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsReader</title>
  
<!--  Ref => http://stackoverflow.com/questions/11110501/rails-3-2-3-load-javascript-from-public-folder-before  -->
<!-- Ref => 黒田・佐藤: 312 -->
  <%#= javascript_include_tag "/keywords" %>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <%#= javascript_include_tag "/js/keywords.js" %>
  <%#= javascript_include_tag "/js/keywords" %>
  <%#= javascript_include_tag "/keywords" %>
  
<!--   <meta charset="euc-jp" /> -->
  
<!--   <meta http-equiv="Content-Type" content="text/html; charset=euc-jp"> -->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
<!--   <meta http-equiv="Content-Type" content="text/html; charset=euc-jp" > -->
</head>
<body>


<%= yield %>

<hr />
<%= link_to_unless_current t('category_label.Genres'), genres_path %>&nbsp;|&nbsp;
<%= link_to_unless_current t('category_label.Categories'), categories_path %>&nbsp;|&nbsp;
<%= link_to_unless_current t('category_label.Subcategories'), subcats_path %>&nbsp;|&nbsp;
<%= link_to_unless_current t('category_label.Keywords'), keywords_path %>
<hr />

<%= link_to 'Back to articles', articles_path %>

<hr />

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsReader</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
<!--   <meta charset="euc-jp" /> -->
  
<!--   <meta http-equiv="Content-Type" content="text/html; charset=euc-jp"> -->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
<!--   <meta http-equiv="Content-Type" content="text/html; charset=euc-jp" > -->
</head>
<body>


<%= yield %>

</body>
</html>